### ISSUE TITLE
Команды и описания для них

### ISSUE THREAD

**Issue by Skumen** [DiscordOOS/RU-Manual-Secutity-Bot-for-Discord#1]
@VlickV, мне нужен список команд (Всех что существуют)

**Comment by VlickV** [comment]
.help - покажет список команд.

Команды для Администраторов бота(ты и я):
.veryfi [id_server] - верификацирует сервер открывая доступ к использованию бота.
.delveryfi [id_server] - снимает верификацию с сервера в том числе и удаляет БД с модераторами того сервера.
.addadmin [id_user] - добавляет юзера в список сотрудников OOS, что дает возможность использовать команду add.
.deladmin [id_user] - удаляет юзера из списка сотрудников.

Команды для сотрудников OOS:
.add [id_user] [link] - добавляет юзера в базу нарушителей OOS.
.del [id_user] - удаляет юзера из базы OOS.

Команды для создателей верифицированных серверов:
.addmoder [id_user] - добавляет юзера в список модераторов этого сервера, что дает возможность использовать команду check.
.delmoder [id_user] - удаляет юзера из списка модераторов сервера.
.channel [id_channel] - устанавливает канал для автоматических сообщений бота о зашедших нарушителях.
.rechannel [id_channel] - для изменения канала бота.

Команды для модераторов:
.check [id_user] - проверяет наличие юзера в базе нарушителей OOS.

**Comment by Skumen** [comment]
@VlickV, сяп ❤️
