### ISSUE TITLE
Api для OOS дискорд бота

### ISSUE THREAD

**Issue by ghost** [DiscordOOS/RU-Manual-Secutity-Bot-for-Discord#10]
Для оос нужен api и вот зачем:

* Это позволит создавать пользователям своих ботов, с интеграцией oos без второго бота.
* Это позволит создавать обёртку для самого ооs дискорд бота, т.к. не всем по нраву дефолтное оформление сообщений и реакций бота. Например, после любой команды - просто реакция, никакого подробного сообщение об ошибке или успехе выполнения команды.
* **Api - безопасно использовать.** Api никак не повредит работе оос, т.к. можно просто использовать токенную систему, либо же OAuth - что и то и то позволит отслеживать активность у токена и при подозрении (будь то внезапная смена ip или др.), что исключит передачу токена 3им лицам. Всё это можно автоматически модерировать и замораживать токены.
* Его легко будет открыть для всех пользователей с минимальными доработками, если конечно же структура проекта изначально была вменяемо спроектирована. 
* При использовании api - будет выше шанс выявлять недобросовестных администраторов серверов, которые передают токен 3им лицам.

**Comment by Skumen** [comment]
1) Система простроена на верификации серверов, да мы технически можем верифицировать адм и давать им токен, но верификация адм гораздо сложнее чем верифицировать сервер. 
2) Создание новых возможностей хорошее решение, мы изменим ответ бота на ошибки (Сделаем их более информативными)
3) API технически безопасно. Но мы ставим целью в данный момент получить верификацию бота у Discord для получения галочки и создания более высокого доверия. Так же мы не видим цели открыть возможность парсить нашу базу. Мы создали более безопасные методы для того чтобы проверять пользователей.
