### ISSUE TITLE
Команда для смены языка

### ISSUE THREAD

**Issue by Skumen** [DiscordOOS/RU-Manual-Secutity-Bot-for-Discord#9]
Добавление команды которая локально изменяет язык в боте (При любых оповещениях все сообщения боты должны быть на русском языке. @VlickV, это возможно реализовать ? Запрос пользователя - @!PǗŜĤĮŜŤĮЎ_ĹỖŘĎ#4215

**Comment by Trieveer** [comment]
Вот мультиязычность я б отложил в самый долгий ящик пока что, та и как сделать знаю только в теории.

**Comment by Skumen** [comment]
Хорошо, вопрос пока закрыт и отложен в нашу доску.
